#!/bin/bash

# This script prompt the user repeatedly for how long they want to work
# and after this many minutes have passed, it will prompt them what they
# want to do next and for how long they want to do it.

# It also records the time spent working, the starting time and
# the subject of the work for each day.

set -e

# The directory where the log files are stored.
DATA_DIR="$HOME/.config/sway/loop-snooze-logs"
# Create the log directory if it doesn't exist
mkdir -p "$DATA_DIR"


center() {
    # Center the text passed as the first argument.
    # Second argument is optional, it is the color of the text.
    # If no color is specified, the default is white.
    # Color format is R;G;B, where R, G and B are integers between 0 and 255.
    COLUMNS=$(tput cols)

    local text="$1"
    local color="$2"
    local text_len=${#text}
    local spaces=$(( (COLUMNS - text_len) / 2 ))
    # shellcheck disable=SC2155
    local spaces_str=$(printf "%${spaces}s" " ")
    if [[ -z "$color" ]]; then
        echo -e "${spaces_str}${text}"
    else
        echo -e "${spaces_str}\e[38;2;${color}m${text}\e[0m"
    fi
}

today_log_file() {
    # Return the path to the log file for today.
    file="$DATA_DIR/$(date '+%Y-%m-%d').log"
    touch "$file"
    echo "$file"
}

prompt_next_duration() {
    # Prompt the user for what they want to do next and for how long.
    # Write the task and the duration in the log file.

    clear
    # Make the terminal full screen (with sway)
    swaymsg fullscreen enable

    # Display the current time in BIG using figlet.
    figlet -ctk "$(date '+%H : %M')" -f "$DATA_DIR/basic.flf" | lolcat
    # Display the current date in orange (255, 165, 0), centered.
    center "$(date '+%A, %B %d, %Y')"  # "255;165;0"

    # Display the last tasks done today, if any
    # shellcheck disable=SC2155
    local today_log=$(today_log_file)
    if [[ -f "$today_log" ]]; then
        echo
        echo "Last things done today:"
        tail -n 5 "$today_log"
        echo
    else
        echo
        echo "Nothing done today yet."
        echo
    fi

    # Ask the user what they want to do next
    echo -ne "What do you want to do next?\n> \e[38;2;255;165;0m"
    read -r TASK
    echo -e "\e[0m"

    # Ask the user for how long they want to do it
    # Make sure this is a number smaller than 120
    while true; do
        echo -ne "For how long?\n> \e[38;2;255;165;0m"
        read -r DURATION
        echo -e "\e[0m"
        if [[ "$DURATION" =~ ^[0-9]+$ ]] && [[ "$DURATION" -lt 120 ]]; then
            break
        else
            echo "Please enter a number smaller than 120."
        fi
    done

    # Record the task and the duration in the log file
    echo "$(date '+%H:%M') for $DURATION minutes: $TASK" >> "$today_log"
}


# if --prompt-once is passed, prompt the user once and exit
# otherwise, loop forever
if [[ "$1" == "--prompt-once" ]]; then
    prompt_next_duration
    exit 0
fi


while true; do
    # Open a new terminal window for the prompt with alacritty
    # and retry if the log file has not a new entry (or was created)
    nb_lines=$(wc -l < "$(today_log_file)" || echo 0)
    while true; do
        alacritty -e "$0" --prompt-once 2>/dev/null
        new_nb_lines=$(wc -l < "$(today_log_file)")
        if [[ "$new_nb_lines" -gt "$nb_lines" ]]; then
            break
        fi
    done

    # find the duration of the last task
    today_log=$(today_log_file)
    DURATION=$(tail -n 1 "$today_log" | cut -d' ' -f3)

    echo "sleeping for $DURATION minutes while working on $(tail -n 1 "$today_log" | cut -d' ' -f5-)"
    sleep "$DURATION"m

    paplay "$DATA_DIR/done.wav" &
    notify-send "Time is up!" "You have been working for $DURATION minutes. GG!"
done
